name: autofix.ci

on:
  push:
    branches: [main]

  pull_request:

  workflow_call:
    inputs:
      command:
        required: false
        type: string
        default: pnpm run lint --fix
      os:
        required: false
        type: string
        default: ubuntu-latest
      persist-credentials:
        required: false
        type: boolean
        default: false

jobs:
  autofix:
    runs-on: ${{ inputs.os || 'ubuntu-slim' }}
    permissions:
      contents: read

    steps:
      - name: Setup JS
        uses: vinicunca/workflows/setup-js@main
        with:
          no-frozen-lockfile: true
          persist-credentials: ${{ inputs.persist-credentials }}

      - name: Fix
        run: ${{ inputs.command }}
        if: ${{ inputs.command != '' }}

      - name: Commit
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
