name: Coverage

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: string
        default: pnpm run test --coverage

      build:
        required: false
        type: string
        default: pnpm run build

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup JS
        uses: vinicunca/workflows/setup-js@main

      - name: Build
        run: ${{ inputs.build }}

      - name: Coverage
        run: ${{ inputs.test }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          use_oidc: true
