name: Release Commit
on:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: pnpm run build
      compact:
        required: false
        type: boolean
        default: false
      packages:
        required: false
        type: string
        default: ''
      comment-package-manager:
        required: false
        type: string
        default: ''
      comment-with-dev:
        required: false
        type: boolean
        default: false
      persist-credentials:
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Release Commit
    runs-on: ubuntu-latest

    steps:
      - name: Setup JS
        uses: vinicunca/workflows/setup-js@main
        with:
          persist-credentials: ${{ inputs.persist-credentials }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Publish
        run: pnpm dlx pkg-pr-new@0.0 publish --pnpm ${{ inputs.compact && '--compact' || '' }} ${{ inputs.packages }} ${{ inputs['comment-package-manager'] && format('--packageManager={0}', inputs['comment-package-manager']) || '' }} ${{ inputs['comment-with-dev'] && '--commentWithDev' || '' }}
