name: Unit Test Dogfooding

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  unit-test:
    uses: vinicunca/workflows/.github/workflows/unit-test.yml@main
